apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    service: frontend
  name: frontend
  annotations:
    nethopper.io/tag-edge: 'true'
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend-v1
  sessionAffinity: None
  type: NodePort
