apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    service: backend
  annotations:
    nethopper.io/tag-edge: 'true'
    nethopper.io/service: 'true'
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: backend-v1
